Challenge 5
shahatwork/study-group pull request #5
Opened 2022-11-21 23:29 UTC by shahatwork

- Added logout test case in spec.login file
- Created spec.cart file
- Added 4 test cases in file to test checkout flow
- Added login custom command in commands.js

2022-11-22 10:19 UTC, stefanworkco requested changes

2022-11-22 10:19 UTC, stefanworkco commented on cypress/support/commands.js
> +  cy.get('[data-test="username"]').type("standard_user")
you have two variables here (username, password) so instead of using hard-coded "standard_user" and pass, use the variables. That way, you can call the same function on different user login, just provide diff. parameters when calling login.

2022-11-22 10:19 UTC, stefanworkco commented on cypress/e2e/spec.login.cy.js
> +      cy.get('[data-test="username"]').type('standard_user')
write some more description inside the test case (describe) and test steps (it). Also,  you can use custom command login inside this it (instead of line 32-37)

2022-11-22 10:19 UTC, stefanworkco commented on cypress/e2e/spec.cart.cy.js
> +describe('challenge 5 test case 2', () => {
**describe** description should be something like "Test successful shopping flow" and each **it** (test step) should say what does that step do. So split this one big **it** inside smaller ones, like for example first should be "validate cart badge doesn't exist" then the second it can be to add backpack and validate cart badge displays 1.

2022-11-22 10:20 UTC, stefanworkco commented on cypress/e2e/spec.cart.cy.js
> +describe('challenge 5 test case 2', () => {
Same for other describe/it

2022-11-29 11:43 UTC, milicazivanovic-work reviewed
Love the comments for individual steps, makes it easy to read and understand. In fact, I've corrected some of my code while going through yours :)

2022-11-29 11:43 UTC, milicazivanovic-work commented on cypress/e2e/spec.login.cy.js
> +      cy.get('[data-test="username"]').click()
For type command we don't need to have the .click() beforehand, just: 
`cy.get('[data-test="username"]').type('standard_user')` is enough

2022-11-29 11:43 UTC, milicazivanovic-work commented on cypress/e2e/spec.login.cy.js
> +      cy.get('[id="react-burger-menu-btn"]').click()
For another way of getting the element by id, we can pass the id with prefix #, e.g. the command: `cy.get('#react-burger-menu-btn').click()`

2022-11-29 11:43 UTC, milicazivanovic-work commented on cypress/e2e/spec.cart.cy.js
> +        cy.get('[class="shopping_cart_badge"]').should('not.exist')
For getting the element by class, another way is to use the .(dot) as a prefix, e.g. `cy.get('.shopping_cart_badge').should('not.exist')`

2022-11-29 11:43 UTC, milicazivanovic-work commented on cypress/e2e/spec.cart.cy.js
> +        cy.get('[data-test="firstName"]').click()
Same as in spec.login.cy.js, you can remove the whole `cy.get('[data-test="firstName"]').click()` command before type and it would still work :)

2022-11-29 11:43 UTC, milicazivanovic-work commented on cypress/e2e/spec.cart.cy.js
> +        cy.get('[class="shopping_cart_badge"]').should('exist')
This is OK, but as far as I understood from the task, the badge icon should be verified at the end of the test, after the user clicks the 'Continue' button in the shopping cart.

2022-11-29 19:43 UTC, shahatwork commented on cypress/e2e/spec.login.cy.js
> +      cy.get('[data-test="username"]').click()
Fixed in  'Updated login and cart files based on Milicas feedback' push

2022-11-29 19:43 UTC, shahatwork commented on cypress/e2e/spec.login.cy.js
> +      cy.get('[id="react-burger-menu-btn"]').click()
Fixed in 'Updated login and cart files based on Milicas feedback'

2022-11-29 19:44 UTC, shahatwork commented on cypress/e2e/spec.cart.cy.js
> +        cy.get('[class="shopping_cart_badge"]').should('not.exist')
I updated this in line 80 but missed a few other instances. Not sure what the protocol here is but I'm going to do another small push to fix the remaining instances

2022-11-29 19:44 UTC, shahatwork commented on cypress/e2e/spec.cart.cy.js
> +        cy.get('[data-test="firstName"]').click()
Fixed!

2022-11-29 19:45 UTC, shahatwork commented on cypress/e2e/spec.cart.cy.js
> +        cy.get('[class="shopping_cart_badge"]').should('exist')
Ah good eye! My steps should match the steps in the task now

2022-11-30 11:41 UTC, milicazivanovic-work commented on cypress/e2e/spec.cart.cy.js
>          cy.get('[data-test="postalCode"]').click()
This line can be removed, too, since it is followed by the .type() command

2022-11-30 11:44 UTC, milicazivanovic-work commented on cypress/e2e/spec.cart.cy.js
> +        cy.get('shopping_cart_badge').should('not.exist')
In this case, it works without a class selector, but just to be safe, add a . (dot) before the 'shopping_cart_badge', e.g. `cy.get('.shopping_cart_badge').should('not.exist')`

2022-11-30 16:11 UTC, shahatwork commented on cypress/e2e/spec.cart.cy.js
>          cy.get('[data-test="postalCode"]').click()
Fixed in [Removed unnecessary click in line 48 and added period prefix for shop…] commit

2022-11-30 16:11 UTC, shahatwork commented on cypress/e2e/spec.cart.cy.js
> +        cy.get('shopping_cart_badge').should('not.exist')
Fixed in [Removed unnecessary click in line 48 and added period prefix for shop…] commit

2022-11-30 16:44 UTC, milicazivanovic-work approved these changes
Looks good to me! :)

2022-11-30 17:04 UTC, stefanworkco commented on cypress/e2e/spec.cart.cy.js
> +        cy.url().should('be.equal', 'https://www.saucedemo.com/cart.html')
I noticed that some assertions for url exist in multiple test cases, which is not required (to always assert url). For example, if we check `cy.url().should('be.equal', 'https://www.saucedemo.com/cart.html')` in first TC, no need to do it in other 3.

Also in second TC we do `cy.url().should('be.equal', 'https://www.saucedemo.com/checkout-step-one.html')` and we already checked that in first one.

2022-11-30 17:04 UTC, stefanworkco commented on cypress/e2e/spec.cart.cy.js
> +        cy.login()
when you update login command, here you need to send the credentials as parameters.

2022-11-30 17:04 UTC, stefanworkco commented on cypress/e2e/spec.cart.cy.js
> +    //test4 continue shopping
feel free to remove all this comments before the it() ( `//test4 continue shopping` and the rest) from all specs. We don't need those, that is what the string description inside the it is used for

2022-12-01 08:59 UTC, stefanworkco commented on cypress/support/commands.js
> +  cy.get('[data-test="username"]').type("standard_user")
Instead of `cy.get('[data-test="username"]').type("standard_user")` you should use the parameter, so:
`cy.get('[data-test="username"]').type(username)`
Same with password

2022-12-01 15:49 UTC, stefanworkco commented on cypress/support/commands.js
> +  cy.get('[data-test="username"]').type("username")
it wont work like this (it will give you login error with bad credentials), don't send string ` cy.get('[data-test="username"]').type("username")` but variable `cy.get('[data-test="username"]').type(username)`
Same with pass

2022-12-01 15:58 UTC, shahatwork commented on cypress/support/commands.js
> +  cy.get('[data-test="username"]').type("username")
Didn't test my PR. This is a great exercise! Thanks for being patient lol

2022-12-01 16:43 UTC, merged